//add new book
POST http://localhost:3000/books/3 
Content-Type: application/json

{"name":"The Dunk","description":"Great book for the yorken"}
###
// get all books
GET http://localhost:3000/books

###
//get book by id
Get http://localhost:3000/books/5

###
// Delete book
DELETE http://localhost:3000/books/3

###
PUT http://localhost:3000/books/3
Content-Type: application/json

{"name":"Cars","description":"Yorkens favorite book"}